### ISSUE TITLE
Not a bug but a suggestion. 

### ISSUE THREAD

**Issue by vignesh0025** [alexcican/alexcican.github.com#4]
Why can't you use Openshift Redhat cloud hosting? They give three free gears with Excellent GIT support in-build with PHP and sufficient space and with lots of such different technologies. Just curious. I did'nt find a place where i could give this comment in the article page.

**Comment by alexcican** [comment]
I really need the performance, and GitHub has offered that. However, I can only host static files, so I might give Openshift Redhat a try (haven’t heard of them before). I just need to see if their free plan has a good enough performance.

Thanks for the recommendation.

**Comment by vignesh0025** [comment]
OpenShift is an excellent hosting platform. I am having heavy websites, running in it (for free). look at http://www.tarangg.in  .. I am surprised you haven't heard of open shift..
